
require("./InputForm.module.css");
const styles = {
  container: 'container_fddcfd4b',
  formCard: 'formCard_fddcfd4b',
  formTitle: 'formTitle_fddcfd4b',
  section: 'section_fddcfd4b',
  sectionTitle: 'sectionTitle_fddcfd4b',
  formRow: 'formRow_fddcfd4b',
  formGroup: 'formGroup_fddcfd4b',
  fullWidth: 'fullWidth_fddcfd4b',
  required: 'required_fddcfd4b',
  input: 'input_fddcfd4b',
  select: 'select_fddcfd4b',
  textarea: 'textarea_fddcfd4b',
  dropdownContainer: 'dropdownContainer_fddcfd4b',
  dropdownHeader: 'dropdownHeader_fddcfd4b',
  selectedItems: 'selectedItems_fddcfd4b',
  placeholder: 'placeholder_fddcfd4b',
  selectedTag: 'selectedTag_fddcfd4b',
  removeTag: 'removeTag_fddcfd4b',
  dropdownArrow: 'dropdownArrow_fddcfd4b',
  dropdownList: 'dropdownList_fddcfd4b',
  dropdownItem: 'dropdownItem_fddcfd4b',
  checkbox: 'checkbox_fddcfd4b',
  signatureArea: 'signatureArea_fddcfd4b',
  signaturePadContainer: 'signaturePadContainer_fddcfd4b',
  signatureCanvas: 'signatureCanvas_fddcfd4b',
  signatureInstructions: 'signatureInstructions_fddcfd4b',
  signatureButtons: 'signatureButtons_fddcfd4b',
  clearSignatureBtn: 'clearSignatureBtn_fddcfd4b',
  signatureSaved: 'signatureSaved_fddcfd4b',
  attachmentArea: 'attachmentArea_fddcfd4b',
  attachmentUpload: 'attachmentUpload_fddcfd4b',
  attachmentLabel: 'attachmentLabel_fddcfd4b',
  attachmentButton: 'attachmentButton_fddcfd4b',
  attachmentHint: 'attachmentHint_fddcfd4b',
  fileInfo: 'fileInfo_fddcfd4b',
  fileName: 'fileName_fddcfd4b',
  removeFileBtn: 'removeFileBtn_fddcfd4b',
  hiddenInput: 'hiddenInput_fddcfd4b',
  actionBar: 'actionBar_fddcfd4b',
  cancelBtn: 'cancelBtn_fddcfd4b',
  submitBtn: 'submitBtn_fddcfd4b'
};

export default styles;
